### ISSUE TITLE
LAN play implementation

### ISSUE THREAD

**Issue by Dr-Wily** [PretendoNetwork/Pretendo#1]
Hello,
Few years ago I helped implement LAN play in AltWFC. Finaly, [it works flawlessly with 12 Wii](https://www.asso-sc.com/wp-content/uploads/2017/12/stun2k16-06.jpg) without any error or disconnection.

I would like to know if Pretento can handle LAN play. I mean only in local network without internet connection and with a server who accept multiples connections from the same subnet.

thanks

**Comment by SuperMarioDaBom** [comment]
Hello,
Unfortunately, Pretendo isn't in a working state ATM. Once we get the core services working as it should normally, I don't see how LAN would be impossible.

**Comment by Dr-Wily** [comment]
Yes I know Pretendo it's not ready yet. It's just a question ;)
I ask because on AltWFC there is some issues where multiple Wii are on the same subnet.
