### ISSUE TITLE
Quazal's URL leads to a shady website.

### ISSUE THREAD

**Issue by Ch0wW** [PretendoNetwork/Pretendo#11]
Greetings!

After clicking on Quazal's URL from `README.md`, it leads to a shady website related to Casinos. 

![image](https://user-images.githubusercontent.com/2938006/190174364-5d47f80d-c878-496f-b71d-889cff29cd2a.png)

After checking the whois infos, the domain was bought back by a malicious entity in 2021. I think it'd be best not to show its URL anymore.

![image](https://user-images.githubusercontent.com/2938006/190176871-a8b7243c-7222-44cc-94cc-776b0beca198.png)

**Comment by Hoot679** [comment]
I scanned the website with VirusTotal, it seems to be fine, however I still agree it should be removed.
