### ISSUE TITLE
When singing in on Wii U, this error appears.

### ISSUE THREAD

**Issue by SwirlyStone5877** [PretendoNetwork/Pretendo#17]
102-2571, "The NNID you entered is already in use. Please enter a different ID."

**Comment by MegamanXGold** [comment]
Similar error when trying to link my 3DS with Pretendo, my first device:

Error Code: 022-2571

The Nintendo Network ID you
entered is already in use.

Please try again.

**Comment by SwirlyStone5877** [comment]
This was a few months ago. I'm now realizing that I was signing up instead of signing in.
