### ISSUE TITLE
Error 102-2482

### ISSUE THREAD

**Issue by BlocBlocTheBloc0** [PretendoNetwork/Pretendo#20]
FR : 
J'ai suivi le tutoriel sur votre site pour installer Pretendo sur ma Wiiu, j'ai mis le fichier nimble dans la sd, crée un compte Pretendo et crée un nouveau compte sur ma wiiu.
Malgré tout j'obtient le code d'erreur suivant :

Code d'erreur : 102-2482

Une erreur est survenue.

Réessayez ultérieurement.

[...]

Information sur l'erreur :
1 5.5.5 E
2 WUP-001 (03)
3 GEM101012292
4 AGMK-1250-7073

ENG :
I followed the tutorial on your site to install Pretendo on my Wiiu, I put the nimble file in the sd, create a Pretendo account and create a new account on my wiiu.
Nevertheless I get the following error code:

Error code: 102-2482

An error has occurred.

Try again later.

[...]

Error Information:
1 5.5.5 E
2 WUP-001 (03)
3 GEM101012292
4 AGMK-1250-7073

PS :
This is a European wiiu (Frensh)
Hacked with Tiramisu

Note : I tried to formulate as best I could because I am French 🥖

**Comment by old-kid-11-years-old** [comment]
do you fond a solution

**Comment by Cristonimus** [comment]
I thinki found out why this error is happening, you see, the public beta has ended, therefore, only the people with the "super mario" upgrade are able to use the servers. This means that, unless you pay 10 USD per month you wont be able to use pretendo servers for now. I think they will, eventually, make it public again, but i have no idea about when will that happen.

**Comment by MilesTailsFan2005** [comment]
alrighty at least i know i gotten it almost ready if that happens again!
