### ISSUE TITLE
Nimbus not switching to Pretendo Network

### ISSUE THREAD

**Issue by grayhax** [PretendoNetwork/Pretendo#28]
I was going to switch from Nintendo Network to Pretendo Network since my 3ds got banned from the Nintendo Network servers. 

But when I touch "Pretendo Network", it restarts (as usual), and then when I check back to see if it switched to Pretendo Network, its still on Nintendo Network!

What do I do and how do I fix this?!

**Comment by grayhax** [comment]
Here is a solution: Hold Select and enable external firms and modules, If you are on Luma3DS 12.0, Update to Luma3DS 12.0.1. Press start to save the settings and merge the luma and titles folder, then put Nimbus and friendaccountmanger in 3ds, then load friendaccountmanager and let it load Pretendo Network, The console is banned due to it being on Pretendo Network and your using an NNID instead of it being on PNID, This isnt a ban, You can get unbanned by switching Nimbus to Pretendo Network, If you want to go back to NNID, Load friendaccountmanager and Nimbus to Nintendo Network.

**Comment by ilonachan** [comment]
> put Nimbus and friendaccountmanger in 3ds, then load friendaccountmanager and let it load Pretendo Network

This may be a dumb question, but what is "friendaccountmanager"? Do you mean the project Nimbus was forked from? Because that doesn't have any releases, and I can't build it.

My issue with Nimbus is less that it "restarts but doesn't switch", and more that it "crashes as soon as I click the button", but because I haven't seen it working I can't tell if there's a difference. If I can track down this "friendaccountmanager", could it help fix the problem?

**Comment by kitkatto9** [comment]
Enable External Firms and modules.

**Comment by ilonachan** [comment]
I followed the guide exactly, except I installed Nimbus via Universal-Updater and then downloaded the package with the other files anyway just to be sure I have the right ones. And yes I checked both of the boxes in Luma, it still crashes.

**Comment by kitkatto9** [comment]
Try installing Nimbus through the github page.

**Comment by ilonachan** [comment]
you mean install the CIA that was in the package? I hadn't actually thought of that, assumed UU would be the same CIA... probably is, because I just tried and it's the same problem. I think I'll also try running the 3dsx version for good measure.

**Comment by kitkatto9** [comment]
Really wouldn't hurt to try the files on the Nimbus releases page.

**Comment by ilonachan** [comment]
yeah, I've tried the CIA now, but I'm just noticing that (completely unrelated) the homebrew launcher doesn't open for me. I'll try to look into that tomorrow, but if that also doesn't work (which I expect) do you have any other ideas I can try? Thanks alot btw

**Comment by kitkatto9** [comment]
If that doesn't work, I'm outta ideas.

**Comment by ilonachan** [comment]
This is basically the problem described in https://github.com/PretendoNetwork/Pretendo/issues/24 right? You solved that eventually, correct? Any idea how?

**Comment by kitkatto9** [comment]
Just enable External Firms and Modules.

**Comment by ilonachan** [comment]
Funny enough, I just learned (hinted at by [this GBATemp comment](https://gbatemp.net/threads/cannot-use-the-homebrew-launcher-if-you-are-seeing-this-luma3ds-is-not-configured-to-load-the.582795/post-9366099)) that apparently that's the reason why I can't open the homebrew launcher?? Anyway, I understand that (and why) this option is necessary, but there's gotta be something else I'm missing... big thanks anyway!

**Comment by kitkatto9** [comment]
You're welcome.

**Comment by jonbarrow** [comment]
If you're having an honest to god *crash*, start from scratch and work your way back up. Reinstall Luma, remove all homebrew/patches and add them back one by one, etc. That kind of thing. Up until things begin to break

Enabling the Luma options mentioned here is 100% required as it's what actually loads our IPS patches

If you're getting a real crash, I would start with Luma. We only officially support the latest version of Luma which at this time is version 13. If you aren't on stock Luma, or your version isn't version 13, then I would start there
