### ISSUE TITLE
[Question] Do you plan on adding support for DS/DSi games as well?

### ISSUE THREAD

**Issue by TSRBerry** [PretendoNetwork/Pretendo#34]
As the title says, I'm curious about whether you plan on adding replacement servers for DS/DSi games as well?

I'm mostly curious about the Pokémon games like black and white, which had features like the [dream world](https://www.serebii.net/blackwhite/dreamworld.shtml) or of course online battles and trades.

**Comment by c08oprkiua** [comment]
No that's what Wiimmfi is for, and the FAQ in the Discord also answers this

**Comment by TSRBerry** [comment]
Thank you, I'll check Wimmfi then! 


I'm not in the discord and since that's not searchable I couldn't answer this question without asking here.
