### ISSUE TITLE
Error Code 022-2482 on Nintendo 2DS

### ISSUE THREAD

**Issue by GamingFan3926** [PretendoNetwork/Pretendo#35]
A family member of mine recently installed Pretendo on their Nintendo 2DS. While attempting to load Nintendo Badge Arcade, they got an error message with the error code listed above.
Does anyone know how to fix this?

**Comment by CheezyFriez12** [comment]
Nintendo Badge Arcade is currently not supported by Pretendo Network. You can see the supported games [here](https://pretendo.network/progress)

**Comment by GamingFan3926** [comment]
Ah, ok.
