### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by Doomsdayrs** [PretendoNetwork/Pretendo#41]
Instead of relying on a single server, a federation might be super useful?

Completely understand if this is impossible due to API constraints etc, just want conversation here.

Similar Issue, ActivityPub for MiiVerse: https://github.com/PretendoNetwork/miiverse-api/issues/34

**Comment by Doomsdayrs** [comment]
Similar Issue: https://github.com/PretendoNetwork/miiverse-api/issues/34

**Comment by jonbarrow** [comment]
The only place this would really make sense would be in Miiverse. So I'm going to close this issue here and just continue over on your other issue
