### ISSUE TITLE
[FEATURE REQUEST] Support for streetpass?

### ISSUE THREAD

**Issue by Glich440** [PretendoNetwork/Pretendo#43]
Does this proyect have any plans to support 3ds street pass? This system was shutdown years ago and it is necessary to access some content in certain games.

**Comment by jonbarrow** [comment]
StreetPass is not shut down. It cannot be shut down. It is a local service. If you aren't getting streetpasses, it means either you aren't taking your 3DS outside when you leave the house or you just haven't passed someone who also has theirs

**Comment by Glich440** [comment]
What about spotpass?
