### ISSUE TITLE
[Request] Add discord rich presence support

### ISSUE THREAD

**Issue by Holmium67** [PretendoNetwork/Pretendo#49]
On the Nintendo Network, there used to be a bot that, when friended, allowed you to show your game status on discord. Now, since pretendo owns their own server implementation, could it be possible to link your discord to your pretendo account and make use of the rich presence api?

**Comment by jonbarrow** [comment]
We have no current plans to do this ourselves. However 3rd party tools are welcome to try and implement it

> there used to be a bot that, when friended

I believe you mean the bot used for https://github.com/MCMi460/3DS-RPC? At a later point I plan to expose some API endpoints that will allow this service to continue without needing the bot. I've already been in contact with the maintainer
